Repository GetFeedback/kahpp-oss, pull requests merged in 2022-08, with the labels that each got.

#136 Introduce kahpp-docker module
  .github/workflows/publish.yml
  README.md
  examples/kahpp-docker-example/docker-compose.yaml
  examples/kahpp-docker-example/kahpp/application.yaml
  kahpp-docker/build.gradle
  kahpp-docker/launch-script.sh
  settings.gradle
Labels: Feature

#164 Introduce latest tag on docker image publishing
  kahpp-docker/build.gradle
Labels: Feature

#165 Fix docker image registry
  kahpp-docker/build.gradle
Labels: Bug

#168 Update dependabot config
  .github/dependabot.yml
Labels: Dependencies

#179 Small changes
  .github/workflows/documentation.yml
  README.md
  docs/developer-guide/spring-boot-starter.md
  docs/features/filters.md
  docs/features/http.md
  docs/features/step.md
  docs/index.md
  examples/kahpp-docker-example/docker-compose.yaml
Labels: Documentation

#185 Improve split step
  .github/CODEOWNERS
  docs/features/transformers.md
  kahpp-spring-autoconfigure/src/main/java/dev/vox/platform/kahpp/configuration/transform/FlatRecordTransform.java
  kahpp-spring-autoconfigure/src/main/java/dev/vox/platform/kahpp/configuration/transform/SplitValueTransform.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/unit/configuration/transform/SplitValueTransformTest.java
Labels: Feature

#189 Add documentation for routing capability
  docs/features/routing.md
  mkdocs.yml
Labels: Documentation

#190 Improve abstract http call
  docs/features/http.md
  kahpp-spring-autoconfigure/src/main/java/dev/vox/platform/kahpp/configuration/http/AbstractHttpCall.java
  kahpp-spring-autoconfigure/src/main/java/dev/vox/platform/kahpp/configuration/http/HttpCall.java
  kahpp-spring-autoconfigure/src/main/java/dev/vox/platform/kahpp/configuration/http/HttpCallStepProcessor.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/KaHPPMockServer.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpConditionalTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpForwardAndNotProduceErrorTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpForwardAndProduceErrorTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpMetricsTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpNotForwardAndNotProduceErrorTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpNotForwardAndProduceErrorTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/integration/http/HttpResponseHandlerTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/unit/configuration/http/ResponseHandlerRecordRouteTest.java
  kahpp-spring-autoconfigure/src/test/java/dev/vox/platform/kahpp/unit/configuration/http/SimpleHttpCallTest.java
Labels: Feature

#191 Add topic declaration to routing docs
  docs/features/routing.md
Labels: Documentation
